name: GitHub Metrics
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write 
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: jfachard
          template: classic
          base: header, activity, repositories
          config_timezone: Europe/Paris 
          
          # Activit√©
          plugin_activity: yes
          plugin_activity_limit: 5
          
          # Langages
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_languages_threshold: 1%
          plugin_languages_sections: most-used
          plugin_languages_colors: github 
          
          plugin_notable: yes
          plugin_notable_indepth: yes
          
          plugin_achievements: yes
          plugin_achievements_threshold: C
          plugin_achievements_display: compact
          plugin_achievements_limit: 0 